### ISSUE TITLE
one liner to add classificiation number per user

### ISSUE THREAD

**Issue by crowston** [mzevin1/GravitySpy#9]
I found a one-liner in pandas to add the classification number:
classification_data['classification_number'] = classification_data.groupby('user_name').cumcount()

**Comment by scottcoughlin2014** [comment]
cool always like one liners! We will get this added. Was trying to make it a one liner without a loop but couldnt quite figure it out

**Comment by crowston** [comment]
I stumbled across a StackExchange discussion that mentioned it.
